### ISSUE TITLE
스플래시 액티비티 버그

### ISSUE THREAD

**Issue by zozero94** [ZeroFriends/GoStopCalculator#6]
가끔 Crash 및 자꾸 다시켜지는 버그 있음

**Comment by zozero94** [comment]
```
2021-10-04 20:15:31.669 20331-20331/zero.friends.gostopcalculator E/AndroidRuntime: FATAL EXCEPTION: main
    Process: zero.friends.gostopcalculator, PID: 20331
    java.lang.IllegalStateException: no event down from INITIALIZED
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:281)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
        at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.kt:167)
        at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.kt:150)
        at androidx.navigation.NavController.updateBackStackLifecycle$navigation_runtime_release(NavController.kt:902)
        at androidx.navigation.NavController.dispatchOnDestinationChanged(NavController.kt:808)
        at androidx.navigation.NavController.navigate(NavController.kt:1636)
        at androidx.navigation.NavController.navigate(NavController.kt:1528)
        at androidx.navigation.NavController.navigate(NavController.kt:1831)
        at androidx.navigation.NavController.navigate$default(NavController.kt:1826)
        at zero.friends.gostopcalculator.NavigatorKt$Navigator$1$1$1$1$1.invokeSuspend(Navigator.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8595)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by zozero94** [comment]
스플래시 액티비티는 xml구조를 가져간다...?
